<template>
    <div class="fd-scroll" style="height: 100%; overflow-y: auto" @scroll="handlerScroll">
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            clouds
        </div>
        <div>
            test
        </div>
    </div>
</template>

<script>
import scrollMixin from '../../mixin/scrolMixinl' 
    export default {
        mixins: [scrollMixin],
    }
</script>

<style lang="scss" scoped>

</style>